apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db-pod
  namespace: default
  labels:
    app: database
spec:
  serviceName: db-service
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
        - name: postgres
          image: postgres-homelab:15
          imagePullPolicy: Never        # imagem carregada via kind load
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: homelabdb
            - name: POSTGRES_USER
              value: admin
            - name: POSTGRES_PASSWORD
              value: changeme          # em produção use um Secret
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: pgdata
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
